name: "🧹 Chore"
description: "Tarefas de manutenção e ajustes que não alteram comportamento do sistema"
title: "🦆 [CHORE] - "
labels: [ "chore" ]
body:
- type: textarea
  id: descricao
  attributes:
    label: 📝 Descrição Geral
    description: Descrição geral.
    placeholder: |
      1. VISÃO DO USUÁRIO

      COMO: XXX
      QUERO: XXX
      PARA: XXX

      [...]

      2. ANEXOS QUE APOIEM O DESENVOLVIMENTO

      XXX

      3. REGRAS DE NEGÓCIO

      XXX

      4. DEPENDÊNCIAS E RISCOS

      XXX

      5. CRITÉRIO DE ACEITE

      DADO: XXX
      QUANDO: XXX
      ENTÃO: XXX

      [...]
  validations:
    required: true

- type: markdown
  attributes:
    value: |
      ### ⌚ DOR

      - História criada utilizando o template de escrita.
      - História refinada, quebrada nas subtarefas.
      - História alinhada com o time/interessados.
      - Mapeamento das APIs, serviços e definições arquiteturais impactadas pela história e procedimentos de publicação.
      - Ambientes configurados e acessos necessários disponibilizados.
      - Ausência de dependências com outras Histórias inacabadas.
      - Legislação e conformidade verificadas, se aplicável.

      ### ✅ DOD

      - Atendimento e evidências de todos os critérios de aceite.
      - Testes unitários desenvolvidos e executados.
      - Deploy em PRD.
      - Code review realizado.
      - Testes prontos.
      - Documentação atualizada.

- type: dropdown
  id: prioridade
  attributes:
    label: 🗓️ Prioridade
    description: Defina a prioridade.
    options:
    - 🧊 Baixa
    - ⚙️ Média
    - 🔥 Alta
  validations:
    required: true

- type: input
  id: estimativa
  attributes:
    label: ⏱️ Story points
    description: Story points.
    placeholder: "1, 3, 5, 8, 13 ou 21"

- type: markdown
  attributes:
    value: |
      ### Fibonacci Score Table Complexity/Effort Conversion

      | COMPLEXITY  | EFFORT  | PUNCTUATION  |
      | ----------- | ------- | ------------ |
      | L           | L       | 1            |
      | M           | L       | 3            |
      | H           | L       | 5            |
      | L           | M       | 3            |
      | M           | M       | 8            |
      | H           | M       | 13           |
      | L           | H       | 5            |
      | M           | H       | 13           |
      | H           | H       | 21           |

        - L = Low
        - M = Medium
        - H = High

        **NOTA:** Acima de 21 pontos, considerar dividir em subtarefas.
