name: "🐞 Bug Fix"
description: "Correção de comportamento inesperado ou erro identificado"
title: "🩹 [FIX] -"
labels: [ "fix" ]
projects:
  - clickpto/Kanban
body:
  - type: textarea
    id: descricao
    attributes:
      label: 📝 Descrição Geral
      placeholder: Descrição Geral
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## ORIENTAÇÕES GERAIS

        ### Preencher formulário "Kanban"

        O formulário "Kanban" estará disponível na própria tarefa após a criação desta.

          - Priority (Requerido)
          - Story Points (Requerido¹)
          - Iteration (Requerido ao liberar para Sprint)
          - Start date (Requerido ao iniciar a atividade)
          - End date (Requerido ao finalizar a atividade)
          - Release (Requerido se roadmap for definido¹)

          ¹ Para atividades de desenvolvimento.

        ### ⌚ DOR

        - História criada utilizando o template de escrita.
        - História refinada, quebrada nas subtarefas.
        - História alinhada com o time/interessados.
        - Mapeamento das APIs, serviços e definições arquiteturais impactadas pela história e procedimentos de publicação.
        - Ambientes configurados e acessos necessários disponibilizados.
        - Ausência de dependências com outras Histórias inacabadas.
        - Legislação e conformidade verificadas, se aplicável.

        ### ✅ DOD

        - Atendimento e evidências de todos os critérios de aceite.
        - Testes unitários desenvolvidos e executados.
        - Deploy em PRD.
        - Code review realizado.
        - Testes prontos.
        - Documentação atualizada.

        ### Fibonacci Score Table Complexity/Effort Conversion (Story Points)

        | COMPLEXITY  | EFFORT  | PUNCTUATION  |
        | ----------- | ------- | ------------ |
        | L           | L       | 1            |
        | M           | L       | 3            |
        | H           | L       | 5            |
        | L           | M       | 3            |
        | M           | M       | 8            |
        | H           | M       | 13           |
        | L           | H       | 5            |
        | M           | H       | 13           |
        | H           | H       | 21           |

          - L = Low
          - M = Medium
          - H = High

          **NOTA:** A partir de 21 pontos, dividir em outras tarefas.
